server:
  port: 8989

spring:
  application.name: API-Gateway
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true 
    netflix:
      ribbon=true
    gateway:
      discovery:        locator:          lower-case-service-id: true
          enabled: true
      routes:
        - id: CREATE-USER
          uri: lb://auth-service
          predicates:
            - Path=/auth/createUser
        - id: GET-TOUR-DETAILS
          uri: lb://tours-service
          predicates:
            - Path=/tours/getAllTours
          filters:
            - AuthenticationFilter
        - id: LOGIN-USER
          uri: lb://auth-service
          predicates:
            - Path=/auth/authenticate


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost